# Generated by Django 3.2.6 on 2021-09-01 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
