# Generated by Django 3.2.6 on 2021-09-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0002_auto_20210901_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Student',
        ),
    ]
