# Generated by Django 3.2.6 on 2021-09-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0003_rename_register_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
