# Generated by Django 3.2.6 on 2021-09-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0005_auto_20210902_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
