# Generated by Django 3.2.6 on 2021-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0007_auto_20210902_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(upload_to='mymedia'),
        ),
    ]
