# Generated by Django 3.2.6 on 2021-09-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0008_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
