# Generated by Django 3.2.6 on 2021-09-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0010_auto_20210902_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
